### ISSUE TITLE
Frame stacking in `test.py`

### ISSUE THREAD

**Issue by emonosuke** [syoamakase/ASR#4]
Function `frame_stacking` seems to expect `(batch_size, seq_len, lmfb_dim)`, but `cpudat` here does not have `batch_size`. (also the number of args mismatches)

https://github.com/syoamakase/ASR/blob/e01c9bfa5261f3c678854694683a48a5ff81c781/test.py#L60

**Comment by syoamakase** [comment]
Thank you for inform me!
I modified the issue. Please check it.

**Comment by emonosuke** [comment]
Runs well. Thank you!
